name: $(Build.BuildId)

variables:
- name: 'AppVersion'
  value: '1.0.[yyyyWW].*'
- name: 'dockerimage'
  value: 'bcinsider.azurecr.io/bcsandbox-master'
- name: 'TestFilter'
  value: '50100..50149'
- name: 'bc_license'
  value: 'C:\vsts-agent-azure\license.flf'

pool:
  name: Warp10

steps:
- checkout: self
  clean: true
  
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       $registry = "bcinsider.azurecr.io"
#       $SecretSettings = @{}
#       $SecretSettings.containerRegistryUserName = $(InsiderUsername)
#       $SecretSettings.containerRegistryPassword = $(InsiderPwd)
      
#       docker login "$registry" -u "$($SecretSettings.containerRegistryUserName)" -p "$($SecretSettings.containerRegistryPassword)"
#     errorActionPreference: 'silentlyContinue'

- task: ALOpsDockerStart@1
  inputs:
    docker_image: '$(dockerimage)'
    docker_login: 'Insider Docker Registry'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc.license)
    
- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: false    

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

- task: ALOpsAppTest@1
  inputs:
    usedocker: true
    import_action: "Skip"
    testfilter: $(TestFilter)
    show_available_tests: true
  continueOnError: true    

- task: PublishTestResults@1
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()    
